--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.0.54.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/10/17 17:53:44
-- Server version: 5.6.34-log
-- Client version: 4.1
--


--
-- Definition for database website
--
DROP DATABASE IF EXISTS website;
CREATE DATABASE IF NOT EXISTS website
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE website;

--
-- Definition for table sys_user
--
CREATE TABLE IF NOT EXISTS sys_user (
  user_id int(11) NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  user_name varchar(20) NOT NULL COMMENT '用户名',
  user_password varchar(50) NOT NULL COMMENT '密码',
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户表';

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;